services:
  scraper:
    build:
      context: .
      dockerfile: Dockerfile.scraper
    container_name: scraper
    environment:
      USER: ${USER}
      PASSWORD: ${PASSWORD}
      DB_HOST: host.docker.internal
      DB_PORT: 4321
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: on-failure
