FROM python:3.14-slim-trixie

ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY requirements_inference.txt .

RUN pip install -r requirements_inference.txt

COPY inference.py neuralnet.py .

CMD ["python3", "inference.py"]