FROM python:3.14-slim-trixie

ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY data/requirements_data.txt .

RUN pip install --no-cache-dir -r requirements_data.txt

COPY data/scraper.py .

CMD ["python3", "scraper.py"]